# SonarQube / SonarCloud Configuration
sonar.projectKey=sfinity-monorepo
sonar.organization=phamleanhkhoa101
sonar.projectName=Sfinity Monorepo
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=backend/src,web-admin/src,mobile/lib
# Path to the test directories
sonar.tests=backend/src/lib/__tests__,mobile/test

# Language-specific configurations
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.dart_tool/**,**/*.spec.ts,**/*.test.ts
sonar.cpd.exclusions=backend/src/openapi.ts
