// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4aUJ39lk7cMubY4vJqAKcIKoWBDvA9M',
    appId: '1:947472672630:web:5506355128c4ff6aa1fc57',
    messagingSenderId: '947472672630',
    projectId: 'mobile-e1ac5',
    authDomain: 'mobile-e1ac5.firebaseapp.com',
    storageBucket: 'mobile-e1ac5.firebasestorage.app',
    measurementId: 'G-VW46TPRED8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ_OvpXu98nrUKPheZOHZ98hLX8g0kB_Y',
    appId: '1:947472672630:android:c05c5553042ad995a1fc57',
    messagingSenderId: '947472672630',
    projectId: 'mobile-e1ac5',
    storageBucket: 'mobile-e1ac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUkNIGMjXTmvowsutpj2wKJ0qeBnofaM',
    appId: '1:947472672630:ios:1c9af125c452c01aa1fc57',
    messagingSenderId: '947472672630',
    projectId: 'mobile-e1ac5',
    storageBucket: 'mobile-e1ac5.firebasestorage.app',
    androidClientId: '947472672630-di3djrljpuuqi03siud058klk3h92bfa.apps.googleusercontent.com',
    iosClientId: '947472672630-opobv1kq76gtinf154nrolj29ei6blcn.apps.googleusercontent.com',
    iosBundleId: 'com.sfinity.sfinity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUkNIGMjXTmvowsutpj2wKJ0qeBnofaM',
    appId: '1:947472672630:ios:1c9af125c452c01aa1fc57',
    messagingSenderId: '947472672630',
    projectId: 'mobile-e1ac5',
    storageBucket: 'mobile-e1ac5.firebasestorage.app',
    androidClientId: '947472672630-di3djrljpuuqi03siud058klk3h92bfa.apps.googleusercontent.com',
    iosClientId: '947472672630-opobv1kq76gtinf154nrolj29ei6blcn.apps.googleusercontent.com',
    iosBundleId: 'com.sfinity.sfinity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG4aUJ39lk7cMubY4vJqAKcIKoWBDvA9M',
    appId: '1:947472672630:web:5506355128c4ff6aa1fc57',
    messagingSenderId: '947472672630',
    projectId: 'mobile-e1ac5',
    authDomain: 'mobile-e1ac5.firebaseapp.com',
    storageBucket: 'mobile-e1ac5.firebasestorage.app',
    measurementId: 'G-VW46TPRED8',
  );

}